env:
  expert_policy_file: ../../../hw1/roble/policies/experts/Ant.pkl
  expert_data: ../../../hw1/roble/expert_data/expert_data_Ant-v2.pkl
  expert_unlabelled_data: ../../../hw1/roble/expert_data/unlabelled/unlabelled_data_Ant-v2.pkl
  exp_name: logprobe_seed2
  env_name: Ant-v2
  max_episode_length: 1000
  render: false
alg:
  loss_name: logprobe
  num_rollouts: 5
  train_idm: false
  do_dagger: true
  num_agent_train_steps_per_iter: 1000
  num_idm_train_steps_per_iter: 10000
  n_iter: 5
  batch_size: 1000
  eval_batch_size: 10000
  train_batch_size: 100
  learning_rate: 0.005
  max_replay_buffer_size: 1000000
  use_gpu: false
  gpu_id: 0
  discrete: false
  ac_dim: 0
  ob_dim: 0
  network:
    layer_sizes:
    - 64
    - 32
    activations:
    - tanh
    - tanh
    output_activation: identity
logging:
  video_log_freq: 5
  scalar_log_freq: 1
  save_params: true
  logdir: /home/mila/i/ivan.anokhin/robot_learning/hw1/data/q2_dagger_ant
  random_seed: 2
  exp_name: q2_dagger_ant
