env:
  expert_policy_file: ../../../hw1/roble/policies/experts/Humanoid.pkl
  expert_data: ../../../hw1/roble/expert_data/expert_data_Humanoid-v2.pkl
  env_name: Humanoid-v2
  exp_name: logprobe_seed1_bs1000
  max_episode_length: 1000
  render: false
alg:
  loss_name: logprobe
  num_rollouts: 5
  train_idm: false
  do_dagger: true
  num_agent_train_steps_per_iter: 1000
  num_idm_train_steps_per_iter: 10000
  n_iter: 20
  batch_size: 2000
  eval_batch_size: 10000
  train_batch_size: 1000
  learning_rate: 0.005
  max_replay_buffer_size: 1000000
  use_gpu: true
  gpu_id: 0
  discrete: false
  ac_dim: 0
  ob_dim: 0
  network:
    layer_sizes:
    - 64
    - 32
    activations:
    - tanh
    - tanh
    output_activation: identity
logging:
  video_log_freq: 5
  scalar_log_freq: 1
  save_params: true
  logdir: /home/mila/i/ivan.anokhin/robot_learning/hw1/data/q2_logprobe_seed1_bs1000_Humanoid-v2_25-01-2024_16-08-48
  random_seed: 1
  exp_name: q2_logprobe_seed1_bs1000_Humanoid-v2_25-01-2024_16-08-48
